-- MySQL Script generated by MySQL Workbench
-- Thu Aug  5 22:02:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_mtto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_mtto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mtto` DEFAULT CHARACTER SET utf8 ;
USE `db_mtto` ;

-- -----------------------------------------------------
-- Table `db_mtto`.`tbl_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mtto`.`tbl_personal` (
  `personal_id` INT NOT NULL AUTO_INCREMENT,
  `personal_nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`personal_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mtto`.`tbl_operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mtto`.`tbl_operador` (
  `operador_id` INT NOT NULL AUTO_INCREMENT,
  `operador_nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`operador_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mtto`.`tbl_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mtto`.`tbl_vehiculo` (
  `vehiculo_id` INT NOT NULL AUTO_INCREMENT,
  `vehiculo_placa` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`vehiculo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mtto`.`tbl_falla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mtto`.`tbl_falla` (
  `falla_id` INT NOT NULL AUTO_INCREMENT,
  `falla_kilometraje` DOUBLE NOT NULL,
  `falla_fecha_registro` DATETIME NULL,
  `falla_fecha_recepcion` DATETIME NULL,
  `tbl_personal_personal_id` INT NOT NULL,
  `tbl_operador_operador_id` INT NOT NULL,
  `tbl_vehiculo_vehiculo_id` INT NOT NULL,
  PRIMARY KEY (`falla_id`),
  CONSTRAINT `fk_tbl_falla_tbl_personal`
    FOREIGN KEY (`tbl_personal_personal_id`)
    REFERENCES `db_mtto`.`tbl_personal` (`personal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_falla_tbl_operador1`
    FOREIGN KEY (`tbl_operador_operador_id`)
    REFERENCES `db_mtto`.`tbl_operador` (`operador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_falla_tbl_vehiculo1`
    FOREIGN KEY (`tbl_vehiculo_vehiculo_id`)
    REFERENCES `db_mtto`.`tbl_vehiculo` (`vehiculo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mtto`.`tbl_tipo_falla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mtto`.`tbl_tipo_falla` (
  `tf_id` INT NOT NULL AUTO_INCREMENT COMMENT 'tipo de falla id',
  `tf_nombre` VARCHAR(255) NULL COMMENT 'tipo de falla nombre',
  PRIMARY KEY (`tf_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mtto`.`tbl_tipo_falla_componente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mtto`.`tbl_tipo_falla_componente` (
  `tfc_id` INT NOT NULL AUTO_INCREMENT,
  `tfc_nombre` VARCHAR(45) NOT NULL,
  `tbl_tipo_falla_tf_id` INT NOT NULL,
  PRIMARY KEY (`tfc_id`),
  CONSTRAINT `fk_tbl_tipo_falla_componente_tbl_tipo_falla1`
    FOREIGN KEY (`tbl_tipo_falla_tf_id`)
    REFERENCES `db_mtto`.`tbl_tipo_falla` (`tf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mtto`.`tbl_falla_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mtto`.`tbl_falla_detalle` (
  `fd_id` INT NOT NULL AUTO_INCREMENT COMMENT 'falla detalle id',
  `fd_descripcion` MEDIUMTEXT NULL COMMENT 'falla detalle descripcion',
  `tbl_falla_falla_id` INT NOT NULL,
  `tbl_tipo_falla_componente_tfc_id` INT NOT NULL,
  PRIMARY KEY (`fd_id`),
  CONSTRAINT `fk_tbl_falla_detalle_tbl_falla1`
    FOREIGN KEY (`tbl_falla_falla_id`)
    REFERENCES `db_mtto`.`tbl_falla` (`falla_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_falla_detalle_tbl_tipo_falla_componente1`
    FOREIGN KEY (`tbl_tipo_falla_componente_tfc_id`)
    REFERENCES `db_mtto`.`tbl_tipo_falla_componente` (`tfc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
