# Generated by Django 3.2.6 on 2021-08-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_alter_pregunta_fecha_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='fecha_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
