# Generated by Django 3.2.7 on 2021-09-25 00:29

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=100)),
                ('foto', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
