# Generated by Django 3.2.6 on 2021-08-27 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_pedido_usu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='mesa_id',
            field=models.ForeignKey(db_column='mesa_id', on_delete=django.db.models.deletion.RESTRICT, to='api.mesa', verbose_name='Mesa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usu_id',
            field=models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='pedidoplatos',
            name='pedido_id',
            field=models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.RESTRICT, related_name='pedidoplatos', to='api.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoplatos',
            name='plato_id',
            field=models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.RESTRICT, related_name='pedidoplatos', to='api.plato', verbose_name='Plato'),
        ),
    ]
