# Generated by Django 3.2.6 on 2021-08-20 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', max_length=100)),
                ('serie', models.CharField(default='', max_length=100)),
                ('marca', models.CharField(default='', max_length=100)),
                ('modelo', models.CharField(default='', max_length=100)),
                ('procesador', models.CharField(default='', max_length=100)),
                ('memoria', models.CharField(default='', max_length=100)),
                ('disco', models.CharField(default='', max_length=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='equipos.empleado')),
            ],
        ),
    ]
