# Generated by Django 3.2.6 on 2021-08-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
